version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.9
    working_directory: ~/repo
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: pytest tests/
